version: '3.8'

services:
  web:
    container_name: django_container_dev
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    command: python backend/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres_container_dev
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container_dev
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: