version: '3.8'

services:
  web:
    container_name: django_container_prod
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    restart: always
    command: sh -c "cd backend && 
                    gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/backend/static/
      - media_volume:/home/app/web/backend/media/
    expose:
      - 8000
    depends_on:
      - db

  db:
    container_name: postgres_container_prod
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: nginx_container_prod
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/web/backend/static/
      - media_volume:/home/app/web/backend/media/
    depends_on:
      - web

  pg_admin:
    container_name: pg_admin_prod
    image: dpage/pgadmin4:6.20
    restart: always
    env_file:
      - ./.env.prod.db
    ports:
      - "5050:80"
      - "5050:443"


volumes:
  postgres_data:
  static_volume:
  media_volume:
