# Generated by Django 4.1.3 on 2022-12-11 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена всего заказа')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес получения заказа')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания заказа')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время выполнения заказа')),
                ('receipt', models.PositiveSmallIntegerField(choices=[(1, 'Самовывоз'), (2, 'Доставка курьером')], verbose_name='Способ получения')),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'Наличные'), (2, 'Безналичные')], verbose_name='Способ оплаты')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('readiness_status', models.PositiveSmallIntegerField(choices=[(1, 'Принят'), (2, 'Готовится'), (3, 'Готов. Ожидает доставку'), (4, 'Получен клиентом')], default=1, verbose_name='Статус готовности')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество товара')),
                ('price_item', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена 1 товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
