# Generated by Django 4.1.2 on 2023-01-08 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма')),
                ('receipt_method', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Самовывоз'), (2, 'Доставка курьером')], null=True, verbose_name='Способ получения')),
                ('payment_method', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Наличные'), (2, 'Безналичные'), (3, 'Онлайн оплата')], null=True, verbose_name='Способ оплаты')),
                ('order_status', models.PositiveSmallIntegerField(choices=[(1, 'Ожидает подтверждения'), (2, 'Подтвержден'), (3, 'Корзина'), (4, 'Отменен')], default=3, verbose_name='Статус заказа')),
                ('readiness_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Готовится'), (2, 'Готов'), (3, 'Получен')], null=True, verbose_name='Статус готовности')),
                ('payment_state', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания заказа')),
                ('update_component_flag', models.BooleanField(default=False, verbose_name='Флаг обновления компонента')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес получения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['order_status', 'readiness_status', 'creation_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество в заказе')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
