# Generated by Django 4.1.2 on 2023-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Оплата наличными'), (2, 'Оплата картой'), (3, 'Перевод на карту'), (4, 'Онлайн оплата')], null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
