# Generated by Django 4.1.2 on 2023-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method_alter_order_payment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_on_site',
            field=models.BooleanField(default=False, verbose_name='Заказ с сайта'),
        ),
    ]
