# Generated by Django 4.1.2 on 2023-01-26 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время добавления товара'),
        ),
    ]
