# Generated by Django 4.1.2 on 2023-02-10 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 13, 57, 2, 723915, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
