# Generated by Django 4.1.2 on 2023-02-10 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_promo_code_promocode_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 14, 7, 15, 864176, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
    ]
