# Generated by Django 4.1.2 on 2023-02-11 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_promocode_is_valid_alter_promocode_valid_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='flag_static_price',
            field=models.BooleanField(default=False, verbose_name='Статичная цена установлена'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='static_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 16, 25, 33, 903954, tzinfo=datetime.timezone.utc), verbose_name='Действует до'),
        ),
    ]
