# Generated by Django 4.1.2 on 2023-02-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_flag_static_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flag_set_static_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='static_price',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 17, 9, 50, 480676, tzinfo=datetime.timezone.utc), verbose_name='Действует до'),
        ),
    ]
