# Generated by Django 4.1.2 on 2023-02-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_flag_set_static_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='name',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 9, 47, 0, 900025, tzinfo=datetime.timezone.utc), verbose_name='Действует до'),
        ),
    ]
