# Generated by Django 4.1.2 on 2023-03-02 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_promocode_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 11, 36, 16, 165156, tzinfo=datetime.timezone.utc), verbose_name='Действует до'),
        ),
    ]
