# Generated by Django 4.1.2 on 2023-01-08 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Название на английском')),
                ('preview', models.ImageField(upload_to='products/previews', verbose_name='Превью')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена без скидки')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в %')),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена со скидкой')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'На проверке'), (2, 'Доступно'), (3, 'Только под заказ'), (4, 'Недоступно')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Название на английском')),
            ],
            options={
                'verbose_name': 'Категория продукта',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Название на английском')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('new_arrival', models.PositiveSmallIntegerField(default=0, verbose_name='Новое поступление')),
                ('quantity_in_stock', models.PositiveSmallIntegerField(default=0, verbose_name='Запас')),
                ('quantity_of_sold', models.PositiveSmallIntegerField(default=0, verbose_name='Количество проданных')),
                ('available', models.BooleanField(default=False, verbose_name='Доступен')),
                ('show_in_filter', models.BooleanField(default=False, verbose_name='Показывать в фильтре')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['quantity_of_sold'],
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество компонентов')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcomponent', verbose_name='Выбрать цветок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Состав',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('slug', 'id')},
        ),
    ]
