# Generated by Django 4.1.2 on 2023-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=None, max_length=150, null=True, unique=True, verbose_name='Название на английском'),
        ),
    ]
