# Generated by Django 4.1.1 on 2022-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.AddField(
            model_name='flower',
            name='available',
            field=models.BooleanField(default=True, verbose_name=models.When(stock=0, then=False)),
        ),
    ]
