# Generated by Django 4.1.1 on 2022-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_flower_options_flower_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='available',
            field=models.BooleanField(verbose_name=models.Case(models.When(stock=0, then=False), default=True)),
        ),
    ]
