# Generated by Django 4.1.2 on 2023-01-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_in_filter',
            field=models.BooleanField(default=False, verbose_name='Показывать в фильтре'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Название на английском'),
        ),
    ]
