# Generated by Django 4.1.2 on 2023-01-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcategory_show_in_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Название на английском'),
        ),
    ]
