# Generated by Django 4.1.2 on 2023-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_header_description_product_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта в поиске'),
        ),
        migrations.AlterField(
            model_name='product',
            name='header_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок в поиске'),
        ),
    ]
