# Generated by Django 4.1.2 on 2023-02-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_header_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'ordering': ['title'], 'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
    ]
